apiVersion: v1
kind: Service
metadata:
  name: nisit-deeden-frontend
spec:
  type: NodePort
  selector:
    app: nisit-deeden-sveltekit
  ports:
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30090
